apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sns091yav-python
  janus-idp.io/tekton: sns091yav-python
  backstage.io/kubernetes-id: sns091yav-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sns091yav-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
