apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sns091yav-python 
  janus-idp.io/tekton: sns091yav-python
  backstage.io/kubernetes-id: sns091yav-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sns091yav-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  